# These are supported funding model platforms

github: JOELwindows7
patreon: JOELwindows7
open_collective: # Replace with a single Open Collective username
ko_fi: JOELwindows7
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: JOELwindows7
issuehunt: Perkedel/HexagonEngine
otechie: # Replace with a single Otechie username
custom: paypal.me/JOELwindows7
custom: metamask.app.link/send/0x1852cc31A16F9C20e8F2A98b8cE951A3090b2d52
