# https://open.lbry.com/@josephbmanley:b/publish-godot-to-itch-with-github:2
# https://github.com/marketplace/actions/build-godot
# https://github.com/marketplace/actions/butler-push
# HELEP

name: Push to Itch

on:
  push:
    branches:
      - master

jobs:
  godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, win64, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          if [ "$PLATFORM" = "win32" ] || [ "$PLATFORM" = "win64" ]; then
            echo "::set-env name=EXPORT_SUFFIX::.exe"
          fi
      - name: Build Godot Project
        uses: josephbmanley/build-godot-action@v1.4.0
        id: godot_build
        with:
          name: hexagon-engine_${{ matrix.platform }}_GitHub-Action${{ env.EXPORT_SUFFIX }}
          preset: ${{ matrix.platform }}
          projectDir: ./ 
          # We settled git from root
          debugMode: 'true'
      - name: Push to Itch
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          CHANNEL: ${{ matrix.platform }}-GitHubAction
          ITCH_GAME: hexagon-engine
          ITCH_USER: joelwindows7
          PACKAGE: ${{ github.workspace }}/${{ steps.godot_build.outputs.build }}
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}